### PR TITLE
adding qtip options #34

### PR DESCRIPTION
**Pull request by StoicLoofah**
Adding functionality for #34 

@yosva does this work for you?

### CODE REVIEW

**Comment by Padhraic** [comment]
I think you need to bump the patch number up to 4 (0.1.4) in the package.json before you merge. Other that that is looks ok to me.

**Comment by yosva** [comment]
Hi!

Sorry for delayed response. Yes, this is Ok, thanks. But for now chronoline is not adapted to my requirements. I've tryed always visible qTip, but now tooltips overlaps each other. I've not time in this moment to try to fix that. Now I'm using VIS timelines... my projet deadline is next. Sorry! and thanks for sharing your work.

Regards,
Yovanis

**Comment by StoicLoofah** [comment]
@Padhraic think this change is still worth shipping, or should i close this PR?

**Comment by Padhraic** [comment]
Sure why not. Somebody will use it.

**Pull request merged**
